package cxf.natv.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-10-23T13:35:02.511+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://service/", name = "WetherService")
@XmlSeeAlso({ObjectFactory.class})
public interface WetherService {

    @WebMethod
    @RequestWrapper(localName = "findCityByZipcode", targetNamespace = "http://service/", className = "cxf.natv.client.stub.FindCityByZipcode")
    @ResponseWrapper(localName = "findCityByZipcodeResponse", targetNamespace = "http://service/", className = "cxf.natv.client.stub.FindCityByZipcodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String findCityByZipcode(

        @WebParam(name = "arg0", targetNamespace = "")
        String arg0
    );
}
